FROM node:22 AS Builder
ARG DIR=/app
WORKDIR ${DIR}
COPY package.json .
RUN npm install
COPY app.js server.js store.js pricing.js db.js .
FROM node:22-alpine
WORKDIR /user
COPY --from=Builder /app/node_modules .
COPY --from=Builder /app/app.js /app/server.js /app/store.js /app/pricing.js /app/db.js .
EXPOSE 3000
CMD [ "npm" , "start"]
