FROM node:22-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit -dev-dependenceis
COPY app.js ./app.js
COPY store.js ./store.js
COPY pricing.js ./pricing.js
COPY server.js ./server.js
COPY db.js ./db.js
COPY index.html ./index.html
COPY styles.css ./styles.css
COPY assets ./assets
EXPOSE 3000
CMD ["node","server.js"]
