
apiVersion: v1 
kind: Secret 
metadata: 
  name: github-secret
  namespace: redbus
type: kubernetes.io/dockerconfigjson
data: 
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJ2ZW5rYWlhaGt1bmNoYW0xMjMtdGVjaCIsInBhc3N3b3JkIjoiZ2hwXzQ1RGh6NlV3M0NBOGFBS25VSmpENzF5SnJqNm9BTDFiVE1VQSIsImF1dGgiOiJkbVZ1YTJGcFlXaHJkVzVqYUdGdE1USXpMWFJsWTJnNloyaHdYelExUkdoNk5sVjNNME5CT0dGQlMyNVZTbXBFTnpGNVNuSnFObTlCVERGaVZFMVZRUT09In19fQ==
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: db-config
  namespace: redbus
data:
  ACCEPT_EULA: "Y"
  DB_NAME: "RedBusDB"
  DB_HOST: "ssms-svc"
  DB_PORT: "1433"
  DB_USER: "sa"
---
apiVersion: v1 
kind: Secret 
metadata:
  name: db-secret
  namespace: redbus
data:
  MSSQL_SA_PASSWORD: VmVua3lAMjIxOTI3NzA0MDcxOTk5I1JlZEJ1c0FwcERldmVsb3A=
  ADMIN_PASS: VmVua3lAMjIxOTI3NzA0MDcxOTk5I1JlZEJ1c0FwcERldmVsb3A=
  ADMIN_USER: YWRtaW4=
type: Opaque
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: redbus
spec:
  storageClassName: gp3
  resources:
    requests:
      storage: 7Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-db
  namespace: redbus
spec:
  replicas: 1
  updateStrategy: 
    type: RollingUpdate 
  serviceName: ssms-svc
  selector:
    matchLabels:
      app: redbus
  template:
    metadata:
      labels:
        app: redbus
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server:2022-latest
          name: ssms
          ports:
            - containerPort: 1433
              name: ssms-port
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MSSQL_SA_PASSWORD
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: ACCEPT_EULA
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                 configMapKeyRef:
                    name: db-config
                    key: DB_USER
          resources:
            requests:
              cpu: 300m
              memory: 6Gi
            limits:
              cpu: 350m
              memory: 7Gi
          volumeMounts:
            - name: pvc-volume
              mountPath: /external-data
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1 
kind: Service 
metadata: 
  name: ssms-svc
  namespace: redbus
spec:
  clusterIP: None
  selector:
    app: redbus
  ports:
    - name: ssms
      port: 1433
      targetPort: ssms-port
      protocol: TCP
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: redbus-deploy
  namespace: redbus
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      imagePullSecrets:
        - name:  github-secret
      containers:
        - name: app
          image: ghcr.io/venkaiahkuncham123-tech/redbus:v3
          ports:
            - containerPort: 3000 
          imagePullPolicy: Always 
          restartPolicy: OnFailure
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: ADMIN_PASS
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /travelers
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /travelers
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
---
apiVersion: v1 
kind: Service 
metadata:
  name: app-svc
  namespace: redbus
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - name: app
      port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: redbus
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: redbus-deploy
---
apiVersion: v1 
kind: ResourceQuota 
metadata: 
  namespace: redbus
  name: redbus-quota
spec:
  hard: 
    pods: 5
    count/deployments.apps: 2
    count/statefulsets.apps: 2
    configmaps: 5
    secrets: 5
    services: 4
    persistentvolumeclaims: 2
    count/networkpolicies.networking.k8s.io: 1
---
/* apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redbus-netpol
  namespace: redbus
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redbus
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: redbus
          podSelector:
            matchLabels:
              app: front-end
      ports:
        - protocol: TCP
          port: 1433
    
*/
